min_version = "2025.11.3"

[env]
_.file = ".env"
_.python.venv = { path = ".venv", create = true }

[tools]
cmake = "4.2"
make = "4.4"
python = "3.11"

[tasks."setup"]
run = """
#!/usr/bin/env bash

if [ ! -f ".env" ]; then
  cp .env.example .env
fi

pip install -r requirements.txt

pio run
"""
